netZooPy/lioness/lioness.py
=> fix analyze lioness

netZooPy/lioness/lioness.py, netZooPy/panda/panda.py, tutorials/gpupanda/gpuPanda_tutorial.ipynb
- Gpu lioness
- gpu-panda export tweaks
- gpu-panda precision flag
=> Gpu lioness

netZooPy/panda/panda.py
OOP/self bug, fixed so panda_network==force
=> tiny OOP bug fix

README.md, lioness.py, panda.py
- in order to let [panda.py()](https://github.com/netZoo/netZooR/blob/master/R/PANDA.R) and [lioness.py()](https://github.com/netZoo/netZooR/blob/master/R/PANDA.R) in netZooR to use up-to-date netZooPy(based on #96), modify the content of netZoo branch.
- add README.md of this branch.
=> update netZoo branch with GPU PANDA

lioness.py
- add new paramter: save_single_network=False to control whether or not to write out single sample network in txt/npy/mat formats
=> modify netZoo branch

netZooPy/panda/panda.py, tests/test_lioness.py, tests/test_panda.py
Hi @AndMastro,
I created a PR following your suggestion for the fix. Note the new branch called `save-memory` that I created from the devel branch. Please let me know if you have any comments.
=> Save memory

netZooPy/panda/panda.py
hopefully this is what you had in mind for a 'user warning'
=> added user feedback for duplicate gene symbols

netZooPy/lioness/lioness_for_puma.py
fix for https://github.com/netZoo/netzoocloud/issues/30#issuecomment-913749887
=> fix pumalioness alpha

netZooPy/lioness/lioness.py
- fix for https://github.com/netZoo/netzoocloud/issues/31
=> fix lioness coexpression labels

netZooPy/panda/run_panda.py, setup.py
- As a response to https://github.com/netZoo/netZooPy/issues/209
=> fix run panda call

netZooPy/panda/panda.py, netZooPy/panda/run_panda.py
add docs to expected input file as suggested in https://github.com/netZoo/netZooPy/issues/209
=> add docs to expression inout

netZooPy/puma/puma.py
without '.' at the beginning of file name, it doesn't save the files.
folder ./tmp has to be a requirement, or the should the code create it automatically?
=> update save files before computing puma

conda/meta.yaml, netZooPy/command_line.py
=> Add panda out and click dependency

netZooPy/lioness/lioness.py, tests/test_lioness.py
=> fixed saving bug. Testing convergence of all lioness output tables

netZooPy/command_line.py, netZooPy/lioness/lioness.py, tests/test_lioness.py
=> Revert "Add subset lioness "

docs/changelog.rst, netZooPy/command_line.py, netZooPy/panda/panda.py, netZooPy/puma/puma.py, tests/test_lioness.py, tests/test_panda.py
Fixing issue #291 #289 #290 #285
=> Small fixes

netZooPy/command_line.py, netZooPy/lioness/lioness.py, netZooPy/panda/calculations_gpu.py, tests/test_lioness.py
Adding with header option for PANDA CLI and fixing lioness subset names for saving
=> Fix lioness

.gitignore, netZooPy/lioness/lioness.py, netZooPy/panda/panda.py, tests/test_condor.py, tests/test_sambar.py
=> fixing pandas for v2.0.0, removing append

netZooPy/cobra/cobra.py
Changed cobra implementation by using scipy package.
=> Add cobra with scipy

README.md, docs/changelog.rst, docs/functions/api.rst, docs/functions/cli.rst, netZooPy/command_line.py, netZooPy/ligress/bonobo.py
Addressing #335 and #336 + BONOBO docs
=> added bonobo to docs and small readme fix. Added LIONESS examples

docs/requirements.txt
=> fixed readthedocs requirements

netZooPy/bonobo/bonobo.py
=> Fix variance computation in bonobo

netZooPy/panda/panda.py
This adds to #352 .
To avoid further problem, we allow the user to specify the tmp folder explicitly.
=> adding to @newmanno PR for tmp folder

.github/workflows/main.yml, netZooPy/lioness/lioness.py, netZooPy/lioness/onlineCoexpression.py, setup.py, tests/test_lioness.py
adding option to compute online coexpression
=> Add online coexpression
